#!/bin/bash
# 
# rewritelinks
#
# combined with ./rewrite-link, rewrites the boost links to be valid within the
# virtual filesystem that encapsulates the qch documentation
#

case $- in 
	*i*)
		echo "must not execute interactive"
		return
		;;
esac

shopt -s extglob
shopt -s globstar

for item in **; do
	if [[ ! -d $item ]]; then		
		echo -ne "processing $item"
		if ./rewrite-link "${item}"; then
			echo "OK"
		else
			echo "[31;1mFAILED[0m"
		fi		
	fi
done
